columns:
- SummonsNumber
- PlateID
- RegistrationState
- PlateType
- IssueDate
- ViolationCode
- VehicleBodyType
- VehicleMake
- IssuingAgency
- StreetCode1
- StreetCode2
- StreetCode3
- VehicleExpirationDate
- ViolationLocation
- ViolationPrecinct
- IssuerPrecinct
- IssuerCode
- IssuerCommand
- IssuerSquad
- ViolationTime
- TimeFirstObserved
- ViolationCounty
- ViolationInFrontOfOrOpposite
- HouseNumber
- StreetName
- IntersectingStreet
- DateFirstObserved
- LawSection
- SubDivision
- ViolationLegalCode
- DaysParkingInEffect
- FromHoursInEffect
- ToHoursInEffect
- VehicleColor
- UnregisteredVehicle
- VehicleYear
- MeterNumber
- FeetFromCurb
- ViolationPostCode
- ViolationDescription
- NoStandingorStoppingViolation
- HydrantViolation
- DoubleParkingViolation
separator: '|'
